-- ======================================================
-- Bangladesh Divisions & Districts seed
-- Requires tables: divisions, districts (+ triggers)
-- MySQL 8.0+ / InnoDB
-- ======================================================

START TRANSACTION;

-- ---------- Divisions (8) ----------
INSERT INTO divisions (name, short_code, status) VALUES
  ('Barishal',    'BAR', 1),
  ('Chattogram',  'CTG', 1),
  ('Dhaka',       'DHK', 1),
  ('Khulna',      'KHL', 1),
  ('Mymensingh',  'MYM', 1),
  ('Rajshahi',    'RAJ', 1),
  ('Rangpur',     'RNG', 1),
  ('Sylhet',      'SYL', 1)
ON DUPLICATE KEY UPDATE name=VALUES(name), status=VALUES(status);

-- ---------- Districts (64) ----------
-- Note: dist_no & short_code are auto-generated by trigger on insert.

-- Barishal Division (6)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Barishal', 1 FROM divisions WHERE short_code='BAR';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Barguna', 1 FROM divisions WHERE short_code='BAR';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Bhola', 1 FROM divisions WHERE short_code='BAR';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Jhalokathi', 1 FROM divisions WHERE short_code='BAR';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Patuakhali', 1 FROM divisions WHERE short_code='BAR';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Pirojpur', 1 FROM divisions WHERE short_code='BAR';

-- Chattogram Division (11)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Chattogram', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Cox''s Bazar', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Cumilla', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Feni', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Brahmanbaria', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Noakhali', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Lakshmipur', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Chandpur', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Khagrachhari', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Rangamati', 1 FROM divisions WHERE short_code='CTG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Bandarban', 1 FROM divisions WHERE short_code='CTG';

-- Dhaka Division (13)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Dhaka', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Faridpur', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Gazipur', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Gopalganj', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Kishoreganj', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Madaripur', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Manikganj', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Munshiganj', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Narayanganj', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Narsingdi', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Rajbari', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Shariatpur', 1 FROM divisions WHERE short_code='DHK';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Tangail', 1 FROM divisions WHERE short_code='DHK';

-- Khulna Division (10)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Khulna', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Bagerhat', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Satkhira', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Jashore', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Narail', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Magura', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Jhenaidah', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Chuadanga', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Kushtia', 1 FROM divisions WHERE short_code='KHL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Meherpur', 1 FROM divisions WHERE short_code='KHL';

-- Mymensingh Division (4)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Mymensingh', 1 FROM divisions WHERE short_code='MYM';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Jamalpur', 1 FROM divisions WHERE short_code='MYM';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Netrokona', 1 FROM divisions WHERE short_code='MYM';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Sherpur', 1 FROM divisions WHERE short_code='MYM';

-- Rajshahi Division (8)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Rajshahi', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Natore', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Naogaon', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Chapai Nawabganj', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Joypurhat', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Bogura', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Sirajganj', 1 FROM divisions WHERE short_code='RAJ';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Pabna', 1 FROM divisions WHERE short_code='RAJ';

-- Rangpur Division (8)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Rangpur', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Dinajpur', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Thakurgaon', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Panchagarh', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Nilphamari', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Lalmonirhat', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Kurigram', 1 FROM divisions WHERE short_code='RNG';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Gaibandha', 1 FROM divisions WHERE short_code='RNG';

-- Sylhet Division (4)
INSERT INTO districts (division_id, name, status)
SELECT id, 'Sylhet', 1 FROM divisions WHERE short_code='SYL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Moulvibazar', 1 FROM divisions WHERE short_code='SYL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Habiganj', 1 FROM divisions WHERE short_code='SYL';
INSERT INTO districts (division_id, name, status)
SELECT id, 'Sunamganj', 1 FROM divisions WHERE short_code='SYL';

COMMIT;

-- Quick sanity: how many rows?
-- SELECT (SELECT COUNT(*) FROM divisions) AS divisions,
--        (SELECT COUNT(*) FROM districts)  AS districts;
