/* =========================================================
   Business / ID Card / Entrepreneur Details
   MySQL 8.0+  |  utf8mb4  |  InnoDB
   ========================================================= */

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TRIGGER IF EXISTS trg_bi_entrepreneur_details_id_card_no;
DROP TABLE IF EXISTS entrepreneur_details;
DROP TABLE IF EXISTS ID_Card_Types;
DROP TABLE IF EXISTS Business_Types;

SET FOREIGN_KEY_CHECKS = 1;

/* =========================
   1) Master lookups
   ========================= */

CREATE TABLE Business_Types (
  business_type_id   INT UNSIGNED NOT NULL AUTO_INCREMENT,
  business_type      VARCHAR(100) NOT NULL,
  status             TINYINT(1)   NOT NULL DEFAULT 1,
  PRIMARY KEY (business_type_id),
  UNIQUE KEY uq_business_type (business_type),
  CONSTRAINT chk_business_types_status CHECK (status IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE ID_Card_Types (
  ID_Card_Type_id    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_Card_Type_name  VARCHAR(100) NOT NULL,
  status             TINYINT(1)   NOT NULL DEFAULT 1,
  PRIMARY KEY (ID_Card_Type_id),
  UNIQUE KEY uq_id_card_type_name (ID_Card_Type_name),
  CONSTRAINT chk_id_card_types_status CHECK (status IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/* =========================================================
   2) entrepreneur_details
   - One row per (company_id, registration_id).
   - Conditional NOT NULL via CHECKs when do_you_have_business = 1.
   - ID_Card_No auto-generated by trigger:
       LPAD(company_id,4,'0') + '-04-' + LPAD(user_id,7,'0')
     where user_id is read from registration_master.
   - Assumes registration_master has a composite key (company_id, registration_id)
     and columns: company_id, registration_id, user_id.
   ========================================================= */


CREATE TABLE entrepreneur_details (
  id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  company_id                  INT UNSIGNED NOT NULL,
  registration_id             BIGINT UNSIGNED NOT NULL,

  do_you_have_business        TINYINT(1) NOT NULL DEFAULT 0,

  business_type_id            INT UNSIGNED NULL,
  Company_name                VARCHAR(150) NULL,
  Company_Establishment_Year  YEAR NULL,
  Company_address             VARCHAR(255) NULL,
  Company_contact_no          VARCHAR(32) NULL,

  Turn_over                   ENUM('0 - 50k',
                                   '50k - 1 lac',
                                   '1 lac - 5 lac',
                                   '5 lac - 10 lac',
                                   '10 lac - 50 lac',
                                   '50 lac - 1 Cr',
                                   '1 Cr - Above') NULL,

  ID_Card_No                  VARCHAR(20) NULL,  -- auto-set by trigger
  ID_Card_Type_id             INT UNSIGNED NULL,
  ID_Card_delivery_date       DATE NULL,
  ID_Card_delivery_status     TINYINT(1) NOT NULL DEFAULT 0, -- 0=Applied,1=Processing,2=Delivered

  created_at                  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),

  -- One row per registration within a company
  UNIQUE KEY uq_company_reg (company_id, registration_id),

  -- ID card number must be unique if present
  UNIQUE KEY uq_id_card_no (ID_Card_No),

  KEY fk_ent_business_type (business_type_id),
  KEY fk_ent_id_card_type (ID_Card_Type_id),

  -- FK to lookups
  CONSTRAINT fk_ent_business_type
    FOREIGN KEY (business_type_id) REFERENCES Business_Types (business_type_id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT fk_ent_id_card_type
    FOREIGN KEY (ID_Card_Type_id) REFERENCES ID_Card_Types (ID_Card_Type_id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK to registration_master (composite)
  CONSTRAINT fk_ent_registration
    FOREIGN KEY (company_id, registration_id)
      REFERENCES registration_master (company_id, registration_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- Validations
  CONSTRAINT chk_ent_has_business CHECK (do_you_have_business IN (0,1)),
  CONSTRAINT chk_ent_delivery_status CHECK (ID_Card_delivery_status IN (0,1,2)),
  CONSTRAINT chk_ent_est_year CHECK (
    Company_Establishment_Year IS NULL
    OR (Company_Establishment_Year BETWEEN 1950 AND 2155)
  ),

  -- Conditional required fields when do_you_have_business = 1
  CONSTRAINT chk_ent_business_type_required CHECK (
    do_you_have_business = 0 OR business_type_id IS NOT NULL
  ),
  CONSTRAINT chk_ent_company_name_required CHECK (
    do_you_have_business = 0 OR (Company_name IS NOT NULL AND Company_name <> '')
  ),
  CONSTRAINT chk_ent_company_address_required CHECK (
    do_you_have_business = 0 OR (Company_address IS NOT NULL AND Company_address <> '')
  ),
  CONSTRAINT chk_ent_company_contact_required CHECK (
    do_you_have_business = 0 OR (Company_contact_no IS NOT NULL AND Company_contact_no <> '')
  ),
  CONSTRAINT chk_ent_turnover_required CHECK (
    do_you_have_business = 0 OR Turn_over IS NOT NULL
  ),
  CONSTRAINT chk_ent_est_year_required CHECK (
    do_you_have_business = 0 OR Company_Establishment_Year IS NOT NULL
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/* =========================================================
   3) Trigger: generate ID_Card_No before insert
      Format: 0001-04-0000001
        0001  -> LPAD(company_id, 4, '0')
        04    -> fixed code for "entrepreneur"
        0000001 -> LPAD(user_id, 7, '0') read from registration_master
   ========================================================= */

DELIMITER $$

CREATE TRIGGER trg_bi_entrepreneur_details_id_card_no
BEFORE INSERT ON entrepreneur_details
FOR EACH ROW
BEGIN
  DECLARE v_user_id BIGINT UNSIGNED;

  -- Resolve user_id from registration_master
  SELECT rm.user_id
    INTO v_user_id
    FROM registration_master AS rm
   WHERE rm.company_id      = NEW.company_id
     AND rm.registration_id = NEW.registration_id
   LIMIT 1;

  -- If not found, prevent insertion (keeps referential correctness)
  IF v_user_id IS NULL THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'registration_master row not found for (company_id, registration_id)';
  END IF;

  -- Only generate if not already provided
  IF NEW.ID_Card_No IS NULL OR NEW.ID_Card_No = '' THEN
    SET NEW.ID_Card_No =
      CONCAT(
        LPAD(NEW.company_id, 4, '0'),
        '-',
        '04',  -- fixed code for entrepreneur
        '-',
        LPAD(v_user_id, 7, '0')
      );
  END IF;
END$$

DELIMITER ;



-- Business_Types


INSERT INTO Business_Types (business_type, status) VALUES
  ('Sole Proprietorship', 1),
  ('Partnership', 1),
  ('Private Limited Company', 1),
  ('Public Limited Company', 1),
  ('Cooperative', 1),
  ('Non-Profit / NGO', 1);
-- ID_Card_Types
INSERT INTO ID_Card_Types (ID_Card_Type_name, status) VALUES
  ('Silver', 1),
  ('Gold', 1),
  ('Platinum', 1);